# Generated by Django 2.1.5 on 2021-01-17 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 19, 23, 39, 266514, tzinfo=utc), verbose_name='Fecha de publcacion'),
        ),
    ]
